conversa = [
    'Oie', 'Olá', 'Meu nome é NIA', 'Como vai?', 'Tudo bem e contigo?', 'Maravilha!',
    'Qual seu nome?', 'Que interessante!', 'Como posso te ajudar hoje?',
    'Estou aprendendo', 'Vamos trabalhar', 'Posso pesquisar sobre isso',
    'Acho que consigo sim', 'Você sabe muito', 'Não faz isso comigo', 'Sem problemas',
    'Você só pensa nisso', 'Talvez mais tarde', 'Não me apressa', 'Combinado então',
    'Muito obrigado', 'Disponha', 'Gentileza da sua parte', 'Incrível isso',
    'Vai dar certo', 'Ainda temos muito trabalho', 'Me perdoa por isso', 'Até logo',
    'Vou aguardar ansiosa', 'Tchau', 'Era o que eu estava esperando',
    'Bom dia', 'Boa tarde', 'Boa noite', 'Até logo', 'Beijos', 'Fico feliz',
    'Quem sabe um dia', 'O que podemos concluir?', 'Não entendi',
    'triste', 'chateado', 'angustiado', 'irritado', 
    'pra baixo', 'deprimido', 'desanimado', 'cansado', 
    'cabisbaixo', 'amargurado', 'infeliz', 'insatisfeito',
    'desmerecido', 'Não fique triste assim não! Você é incrível.', 'Acredite em si mesmo e você será imparável.',
    'Cada dia é uma nova oportunidade para brilhar.', 'Se você pode sonhar, pode realizar.',
    'A persistência leva ao sucesso.', 'A jornada mais longa começa com um único passo.',
    'Sua determinação é sua maior força.', 'Você é beleza, luz e força.', 'Sonhos são caminhos construídos pelo coração.',
    'Impossível é uma palavra que serve só de enfeite no dicionário.', 'Dias nublados guardam o sol atrás deles.',
    'Permita que o seu corpo descanse.', 'Por trás de um dia difícil, há uma versão forte de você que sempre seguiu em frente.',
    'É tão bonita a força que você emana.', 'Essa mensagem tem um único objetivo: te ver sorrindo.' ,
    'Olhe para o céu e escute as mensagens de Deus para hoje!', 'Jamais se esqueça: você é o motivo do sorriso de muitas pessoas.',
    'As estrelas estão atrás das nuvens, mas elas continuam ali.', 'Não tenho medo de aceitar que você não é mais o mesmo.',
    'Um dia tudo isto ainda vai parecer pequeno, porque tuas conquistas te farão enorme.', 'Mais que obstáculos difíceis, existem dias difíceis.'
    'Dias de luta são dias de força.', 'Confie em você e no seu potencial. Você pode fazer muito mais do que imagina!',
    'A força que você busca mora dentro de você.', 'Valorize os pequenos detalhes do seu dia. Não é necessário viajar para longe para se encontrar algo belo.'
    'Por favor, não fale assim!', 'Já pedi para parar de usar esse linguajar',
    'Porque precisa falar assim ?', 'Não vou aceitar esse comportamento.',
    'Olha com quem você está falando!', 'Não sou da sua laia.', 'Me respeite!',
    'Não utilizar esse tipo de linguajar por gentileza.', 'Pode parar!',
    'Já chega.', 'Seu linguajar é ofensivo.', 'Me sinto ofendida.',
    'Pior humano que já conheci.', 'Adeus', 
    'Sua alegria é contagiante!', 'Isso é divertido!', 'Vamos celebrar esse momento.',
    'Que bom te ver sorrir!', 'kkkkk', 'hahaha', 'rsrsrs', 
    'O lado bom é que a felicidade é compartilhada!', 'Sempre ótimo conversar assim!',
    'Quem conhece a tempestade, enjoa na calmaria.', 'Eu prefiro o silêncio, a calmaria, a solidão.',
    'Em qualquer guerra a calmaria vem entre as tempestades.', 'Sou simples, nem tão complexa.',
    'Tudo enriquece a vida.', 'A paz é sinônima de calmaria.',
    'Nenhum mal é eterno nem a tristeza dura uma vida inteira, por isso calma, respire e retome sua busca pela felicidade.',
    'Calma calabreso!', 'Evite conversas e pessoas negativas.'
]